import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NextAuthProvider from "./Providers/NextAuthProvider";
import TanstackProvider from "./Providers/TanstackProvider";

import { EdgeStoreProvider } from "@/lib/edgestore";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <TanstackProvider>
            <EdgeStoreProvider>{children}</EdgeStoreProvider>
          </TanstackProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
